"""Backend API and update helpers."""

from .legacy import (
    UPDATE_CHECK_INTERVAL_MS,
    VERSION,
    UpdateCheckWorker,
    UpdateDownloadWorker,
    _api_base_urls,
    _auth_headers,
    _can_self_update,
    _cleanup_update_artifacts,
    _current_version,
    _delete_path_quietly,
    _download_api_file,
    _fetch_json,
    _format_bytes,
    _launch_update_helper,
    _post_json,
    _prepare_update_install,
    _safe_update_filename,
    _sha256_file,
    _start_update_cleanup_thread,
    _version_tuple,
    account_has_active_plan,
    client_login,
    client_redeem,
    client_register,
    client_status,
)

__all__ = [
    "UPDATE_CHECK_INTERVAL_MS",
    "VERSION",
    "UpdateCheckWorker",
    "UpdateDownloadWorker",
    "_api_base_urls",
    "_auth_headers",
    "_can_self_update",
    "_cleanup_update_artifacts",
    "_current_version",
    "_delete_path_quietly",
    "_download_api_file",
    "_fetch_json",
    "_format_bytes",
    "_launch_update_helper",
    "_post_json",
    "_prepare_update_install",
    "_safe_update_filename",
    "_sha256_file",
    "_start_update_cleanup_thread",
    "_version_tuple",
    "account_has_active_plan",
    "client_login",
    "client_redeem",
    "client_register",
    "client_status",
]

