"""UI shell, pages, dialogs, and reusable widgets."""

from .legacy import (
    AccountPage,
    AdminRequiredDialog,
    CornerGrip,
    Dashboard,
    FitLabel,
    Hextra,
    HomePage,
    HtmlActivityPage,
    HtmlRestorePage,
    HtmlSettingsPage,
    LoginPage,
    MiniStat,
    MotdOverlay,
    OverviewPage,
    OverviewScoreCard,
    ProfilesPage,
    QuickToolsPage,
    RestorePage,
    RestoreWarnDialog,
    ScoreWidget,
    SettingsPage,
    Sidebar,
    SmoothScrollArea,
    SnowCanvas,
    Toggle,
    TweakPage,
    UpdateAvailableDialog,
    UpdateProgressDialog,
    _Check,
    _Dot,
)

__all__ = [
    "AccountPage",
    "AdminRequiredDialog",
    "CornerGrip",
    "Dashboard",
    "FitLabel",
    "Hextra",
    "HomePage",
    "HtmlActivityPage",
    "HtmlRestorePage",
    "HtmlSettingsPage",
    "LoginPage",
    "MiniStat",
    "MotdOverlay",
    "OverviewPage",
    "OverviewScoreCard",
    "ProfilesPage",
    "QuickToolsPage",
    "RestorePage",
    "RestoreWarnDialog",
    "ScoreWidget",
    "SettingsPage",
    "Sidebar",
    "SmoothScrollArea",
    "SnowCanvas",
    "Toggle",
    "TweakPage",
    "UpdateAvailableDialog",
    "UpdateProgressDialog",
    "_Check",
    "_Dot",
]

