"""Shared build metadata for the Hextra Windows executables.

Every build path (Nuitka .bat, PyInstaller spec, CI workflow) reads the
version and product strings from here so the exe can never drift from
``VERSION`` in :mod:`hextra.legacy`.

Usage::

    python packaging/build_info.py --field version
    python packaging/build_info.py --field artifact
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LEGACY_PY = REPO_ROOT / "hextra" / "legacy.py"

PRODUCT_NAME = "Hextra"
ORIGINAL_FILENAME = "Hextra.exe"
FILE_DESCRIPTION = "Hextra - offline Windows desktop tweaker"
COMPANY_NAME = "Hextra"
_VERSION_RE = re.compile(r'^VERSION\s*=\s*["\']([^"\']+)["\']', re.MULTILINE)


def app_version() -> str:
    """Return the app version declared in ``hextra/legacy.py``."""
    try:
        text = LEGACY_PY.read_text(encoding="utf-8")
    except OSError:
        return "0.0.0"
    match = _VERSION_RE.search(text)
    return match.group(1) if match else "0.0.0"


def version_tuple(version: str | None = None, parts: int = 4) -> tuple[int, ...]:
    """Turn ``1.1.0`` into the ``(1, 1, 0, 0)`` shape Windows resources want."""
    raw = [p for p in re.split(r"[.\-+]", str(version or app_version())) if p != ""]
    numbers = []
    for chunk in raw[:parts]:
        digits = re.match(r"\d+", chunk)
        numbers.append(int(digits.group(0)) if digits else 0)
    while len(numbers) < parts:
        numbers.append(0)
    return tuple(max(0, min(65535, n)) for n in numbers)


def artifact_name(version: str | None = None) -> str:
    """Name used for downloadable build artifacts / releases."""
    return f"{PRODUCT_NAME}-{version or app_version()}-windows-x64.exe"


def render_version_info(version: str | None = None) -> str:
    """Render a PyInstaller ``VSVersionInfo`` file for the given version."""
    version = version or app_version()
    vers = ", ".join(str(n) for n in version_tuple(version))
    return f'''# Generated by packaging/build_info.py - do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({vers}),
    prodvers=({vers}),
    mask=0x3F,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', '{COMPANY_NAME}'),
        StringStruct('FileDescription', '{FILE_DESCRIPTION}'),
        StringStruct('FileVersion', '{version}'),
        StringStruct('InternalName', '{PRODUCT_NAME}'),
        StringStruct('OriginalFilename', '{ORIGINAL_FILENAME}'),
        StringStruct('ProductName', '{PRODUCT_NAME}'),
        StringStruct('ProductVersion', '{version}'),
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ],
)
'''


_FIELDS = {
    "version": app_version,
    "name": lambda: PRODUCT_NAME,
    "filename": lambda: ORIGINAL_FILENAME,
    "artifact": artifact_name,
    "description": lambda: FILE_DESCRIPTION,
    "repo_root": lambda: str(REPO_ROOT),
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--field",
        choices=sorted(_FIELDS),
        default="version",
        help="which build value to print (default: version)",
    )
    parser.add_argument(
        "--version-info",
        action="store_true",
        help="print the PyInstaller VSVersionInfo source instead of a field",
    )
    args = parser.parse_args(argv)
    if args.version_info:
        print(render_version_info(), end="")
    else:
        print(_FIELDS[args.field]())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
